# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Help.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
# import Main_Window
# import About
# import manage


class Ui_Window_help(object):
    # def mainWindow(self):
    #     self.window = QtWidgets.QMainWindow()
    #     self.ui = Main_Window.Ui_MainWindow_main()
    #     self.ui.setupUi(self.window)
    #     self.window.show()
    #     manage.response("")
    #     self.window.close()
        
    # def aboutWindow(self):
    #     self.window = QtWidgets.QMainWindow()
    #     self.ui = About.Ui_Window_about()
    #     self.ui.setupUi(self.window)
    #     self.window.show()
    #     self.str_cont1 = self.ui.label_3.text()
    #     self.str_cont2 = self.ui.label_About.text()
    #     self.str_cont3 = self.ui.label_About_Content.text()
    #     self.window.show()
    #     manage.response("")
    #     manage.response(self.str_cont1)
    #     manage.response("")
    #     manage.response(self.str_cont2)
    #     manage.response(self.str_cont3)
    #     self.window.close()
        
        
    def setupUi(self, Window_Help):
        Window_Help.setObjectName("Window_Help")
        Window_Help.setWindowModality(QtCore.Qt.ApplicationModal)
        Window_Help.resize(553, 579)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Window_Help.sizePolicy().hasHeightForWidth())
        Window_Help.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        Window_Help.setFont(font)
        Window_Help.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Window_Help.setWindowIcon(icon)
        Window_Help.setToolTipDuration(1)
        Window_Help.setStyleSheet("background-color: rgb(223, 223, 223);")
        Window_Help.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        Window_Help.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.centralwidget = QtWidgets.QWidget(Window_Help)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_Help_Heading = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_Help_Heading.setFont(font)
        self.label_Help_Heading.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.label_Help_Heading.setToolTip("")
        self.label_Help_Heading.setToolTipDuration(1)
        self.label_Help_Heading.setWhatsThis("")
        self.label_Help_Heading.setStyleSheet("color: rgb(255, 180, 0);")
        self.label_Help_Heading.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_Help_Heading.setLineWidth(3)
        self.label_Help_Heading.setMidLineWidth(1)
        self.label_Help_Heading.setScaledContents(True)
        self.label_Help_Heading.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Help_Heading.setWordWrap(True)
        self.label_Help_Heading.setObjectName("label_Help_Heading")
        self.gridLayout_3.addWidget(self.label_Help_Heading, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 496, 500))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.label_Help_Content = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.label_Help_Content.setFont(font)
        self.label_Help_Content.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.label_Help_Content.setMouseTracking(True)
        self.label_Help_Content.setTabletTracking(True)
        self.label_Help_Content.setFocusPolicy(QtCore.Qt.TabFocus)
        self.label_Help_Content.setToolTip("")
        self.label_Help_Content.setToolTipDuration(1)
        self.label_Help_Content.setWhatsThis("")
        self.label_Help_Content.setStyleSheet("color: rgb(255, 180, 0);")
        self.label_Help_Content.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_Help_Content.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_Help_Content.setLineWidth(3)
        self.label_Help_Content.setMidLineWidth(1)
        self.label_Help_Content.setScaledContents(True)
        self.label_Help_Content.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_Help_Content.setWordWrap(True)
        self.label_Help_Content.setIndent(1)
        self.label_Help_Content.setObjectName("label_Help_Content")
        self.gridLayout.addWidget(self.label_Help_Content, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        Window_Help.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Window_Help)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 553, 21))
        self.menubar.setObjectName("menubar")
        self.menuVoice_Only = QtWidgets.QMenu(self.menubar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuVoice_Only.sizePolicy().hasHeightForWidth())
        self.menuVoice_Only.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menuVoice_Only.setFont(font)
        self.menuVoice_Only.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.menuVoice_Only.setTabletTracking(True)
        self.menuVoice_Only.setFocusPolicy(QtCore.Qt.TabFocus)
        self.menuVoice_Only.setToolTipDuration(1)
        self.menuVoice_Only.setAutoFillBackground(False)
        self.menuVoice_Only.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.menuVoice_Only.setTearOffEnabled(True)
        self.menuVoice_Only.setToolTipsVisible(True)
        self.menuVoice_Only.setObjectName("menuVoice_Only")
        self.menu_About = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menu_About.setFont(font)
        self.menu_About.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.menu_About.setToolTipDuration(1)
        self.menu_About.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.menu_About.setObjectName("menu_About")
        self.menu_Help_2 = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menu_Help_2.setFont(font)
        self.menu_Help_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.menu_Help_2.setToolTipDuration(1)
        self.menu_Help_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.menu_Help_2.setObjectName("menu_Help_2")
        Window_Help.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Window_Help)
        self.statusbar.setObjectName("statusbar")
        Window_Help.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(Window_Help)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.toolBar.setFont(font)
        self.toolBar.setToolTipDuration(-1)
        self.toolBar.setObjectName("toolBar")
        Window_Help.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menubar.addAction(self.menuVoice_Only.menuAction())
        self.menubar.addAction(self.menu_Help_2.menuAction())
        self.menubar.addAction(self.menu_About.menuAction())
        
        
        # self.menuVoice_Only.addAction(self.menuVoice_Only.menuAction())
        # self.menuVoice_Only.hovered.connect(self.mainWindow)
        # self.menu_About.addAction(self.menu_About.menuAction())
        # self.menu_About.hovered.connect(self.aboutWindow)


        self.retranslateUi(Window_Help)
        QtCore.QMetaObject.connectSlotsByName(Window_Help)

    def retranslateUi(self, Window_Help):
        _translate = QtCore.QCoreApplication.translate
        Window_Help.setWindowTitle(_translate("Window_Help", "AOS 1.0 - Help"))
        Window_Help.setToolTip(_translate("Window_Help", "Main Window"))
        self.label_Help_Heading.setText(_translate("Window_Help", "HELP"))
        self.label_Help_Content.setText(_translate("Window_Help", "\n"
"This part help navigate around the application.\n"
"\n"
"1. Once the application is opened, it initiates the applicationautomatically.\n"
"\n"
"2. To access the software via voice only, click of the \"voice Only\" manu bar or say \"voice  only\".\n"
"\n"
"3. To access the Help section, click of the \"Help\" manu bar or say \"help\".\n"
"\n"
"4. To access the About section, click of the \"About\" manu bar or say \"About\".\n"
"\n"
"5. On the main window page, the  application can be utilised both via text and via voice command.\n"
"\n"
"6. To use the text command, command are typed via a keyboard into the text area and the send button by the side is clicked and the reponse is returned both by speech and text.\n"
"\n"
"7. To use the voice command, command are said out loud and the reponse is returned both by speech and text.\n"
"\n"
"\n"
"\n"
""))
        self.menuVoice_Only.setToolTip(_translate("Window_Help", "Voice Only Command"))
        self.menuVoice_Only.setTitle(_translate("Window_Help", "Main"))
        self.menu_About.setToolTip(_translate("Window_Help", "About"))
        self.menu_About.setTitle(_translate("Window_Help", "About"))
        self.menu_Help_2.setToolTip(_translate("Window_Help", "Help"))
        self.menu_Help_2.setStatusTip(_translate("Window_Help", "Help"))
        self.menu_Help_2.setTitle(_translate("Window_Help", "Help"))
        self.toolBar.setWindowTitle(_translate("Window_Help", "toolBar"))

        
import image_assets

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Window_Help = QtWidgets.QMainWindow()
    ui = Ui_Window_help()
    ui.setupUi(Window_Help)
    Window_Help.show()
    sys.exit(app.exec_())
