# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QMovie
from PyQt5.QtCore import Qt
import Voice_only
import About
import Help
import manage
import time


class Ui_MainWindow_main(object):
    def voiceWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Voice_only.Ui_MainWindow_voice()
        self.ui.setupUi(self.window)
        self.window.show()
        manage.response("")
        time.sleep(1)
        while 1:
            self.query = manage.command()
            manage.reply(self.query)
       
    def aboutWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = About.Ui_Window_about()
        self.ui.setupUi(self.window)
        self.window.show()
        self.str_cont1 = self.ui.label_3.text()
        self.str_cont2 = self.ui.label_About.text()
        self.str_cont3 = self.ui.label_About_Content.text()
        self.window.show()
        manage.response("")
        manage.response(self.str_cont1)
        manage.response("")
        manage.response(self.str_cont2)
        manage.response(self.str_cont3)
        self.window.close()
        
    def helpWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Help.Ui_Window_help()
        self.ui.setupUi(self.window)
        self.window.show()
        self.str_cont1 = self.ui.label_Help_Heading.text()
        self.str_cont2 = self.ui.label_Help_Content.text()
        self.window.show()
        manage.response("")
        manage.response(self.str_cont1)
        manage.response("")
        manage.response(self.str_cont2)
        self.window.close()
    
    def setupUi(self, MainWindow_main):
        MainWindow_main.setObjectName("MainWindow_main")
        MainWindow_main.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow_main.resize(600, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow_main.sizePolicy().hasHeightForWidth())
        MainWindow_main.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        MainWindow_main.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow_main.setWindowIcon(icon)
        MainWindow_main.setToolTipDuration(1)
        MainWindow_main.setStyleSheet("background-color: rgb(223, 223, 223);")
        MainWindow_main.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        MainWindow_main.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow_main)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 270, 551, 121))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setEnabled(True)
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"Verdana\";\n"
"border-color: rgb(255, 180, 0);\n"
"color: rgb(0, 0, 0);")
        self.label.setText("OUT SHOULD APPEAR HERE!")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignHCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 470, 471, 71))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setToolTipDuration(1)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"Verdana\";\n"
"border-color: rgb(255, 180, 0);\n"
"color: rgb(0, 0, 0);")
        
        
        self.lineEdit.setText("   Enter Command here...")
        
        
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_3.addWidget(self.lineEdit)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(480, 470, 82, 72))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_Send = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        # self.pushButton_Send.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Send.sizePolicy().hasHeightForWidth())
        self.pushButton_Send.setSizePolicy(sizePolicy)
        self.pushButton_Send.setMaximumSize(QtCore.QSize(80, 70))
        self.pushButton_Send.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Send.setMouseTracking(True)
        self.pushButton_Send.setTabletTracking(True)
        self.pushButton_Send.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_Send.setToolTipDuration(1)
        self.pushButton_Send.setAutoFillBackground(False)
        self.pushButton_Send.setText("")
        
        self.pushButton_Send.clicked.connect(self.sendMessage)
        
        
        
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/send.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Send.setIcon(icon1)
        self.pushButton_Send.setIconSize(QtCore.QSize(80, 69))
        self.pushButton_Send.setCheckable(False)
        self.pushButton_Send.setAutoDefault(True)
        self.pushButton_Send.setDefault(True)
        self.pushButton_Send.setFlat(False)
        self.pushButton_Send.setObjectName("pushButton_Send")
        self.verticalLayout_4.addWidget(self.pushButton_Send)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 571, 200))
        self.label_2.setToolTipDuration(1)
        self.label_2.setText("")
        self.movie = QMovie(":/newPrefix/listening.gif")
        # self.label_2.setPixmap(QtGui.QPixmap(":/newPrefix/listening.gif"))
        self.label_2.setMovie(self.movie)
        self.startAnimation()
        self.label_2.setScaledContents(True)
        self.label_2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_2.setObjectName("label_2")
        MainWindow_main.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow_main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 590, 21))
        self.menubar.setObjectName("menubar")
        self.menuVoice_Only = QtWidgets.QMenu(self.menubar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuVoice_Only.sizePolicy().hasHeightForWidth())
        self.menuVoice_Only.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menuVoice_Only.setFont(font)
        self.menuVoice_Only.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.menuVoice_Only.setTabletTracking(True)
        self.menuVoice_Only.setFocusPolicy(QtCore.Qt.TabFocus)
        self.menuVoice_Only.setToolTipDuration(1)
        self.menuVoice_Only.setAutoFillBackground(False)
        self.menuVoice_Only.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.menuVoice_Only.setTearOffEnabled(True)
        self.menuVoice_Only.setToolTipsVisible(True)
        self.menuVoice_Only.setObjectName("menuVoice_Only")
        self.menu_About = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menu_About.setFont(font)
        self.menu_About.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.menu_About.setToolTipDuration(1)
        self.menu_About.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.menu_About.setObjectName("menu_About")
        self.menu_Help_2 = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menu_Help_2.setFont(font)
        self.menu_Help_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.menu_Help_2.setToolTipDuration(1)
        self.menu_Help_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.menu_Help_2.setObjectName("menu_Help_2")
        MainWindow_main.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_main)
        self.statusbar.setObjectName("statusbar")
        MainWindow_main.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow_main)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.toolBar.setFont(font)
        self.toolBar.setToolTipDuration(-1)
        self.toolBar.setObjectName("toolBar")
        MainWindow_main.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menubar.addAction(self.menuVoice_Only.menuAction())
        self.menubar.addAction(self.menu_Help_2.menuAction())
        self.menubar.addAction(self.menu_About.menuAction())


        self.menuVoice_Only.addAction(self.menuVoice_Only.menuAction())
        self.menuVoice_Only.hovered.connect(self.voiceWindow)
        self.menu_About.addAction(self.menu_About.menuAction())
        self.menu_About.hovered.connect(self.aboutWindow)
        self.menu_Help_2.addAction(self.menu_Help_2.menuAction())
        self.menu_Help_2.hovered.connect(self.helpWindow)
        
        

        self.retranslateUi(MainWindow_main)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_main)

    def retranslateUi(self, MainWindow_main):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_main.setWindowTitle(_translate("MainWindow_main", "AOS 1.0 - Main"))
        MainWindow_main.setToolTip(_translate("MainWindow_main", "Main Window"))
        self.menuVoice_Only.setToolTip(_translate("MainWindow_main", "Voice Only Command"))
        self.menuVoice_Only.setTitle(_translate("MainWindow_main", "Voice Only"))
        self.menu_About.setToolTip(_translate("MainWindow_main", "About"))
        self.menu_About.setTitle(_translate("MainWindow_main", "About"))
        self.menu_Help_2.setToolTip(_translate("MainWindow_main", "Help"))
        self.menu_Help_2.setStatusTip(_translate("MainWindow_main", "Help"))
        self.menu_Help_2.setTitle(_translate("MainWindow_main", "Help"))
        self.toolBar.setWindowTitle(_translate("MainWindow_main", "toolBar"))
        
    def startAnimation(self):
        self.movie.start()
        
    def sendMessage(self):
        self.str_cont = self.lineEdit.text().lower()
        manage.reply(self.str_cont)
        
        
import image_assets


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow_main = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_main()
    ui.setupUi(MainWindow_main)
    MainWindow_main.show()
    sys.exit(app.exec_())
