# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Voice_only.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QMovie
from PyQt5.QtCore import Qt
import Main_Window
import About
import Help
import manage

class Ui_MainWindow_voice(object):
    def mainWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Main_Window.Ui_MainWindow_main()
        self.ui.setupUi(self.window)
        self.window.show()
        manage.response("")
        self.window.close()
        
    def aboutWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = About.Ui_Window_about()
        self.ui.setupUi(self.window)
        self.window.show()
        self.str_cont1 = self.ui.label_3.text()
        self.str_cont2 = self.ui.label_About.text()
        self.str_cont3 = self.ui.label_About_Content.text()
        self.window.show()
        manage.response("")
        manage.response(self.str_cont1)
        manage.response("")
        manage.response(self.str_cont2)
        manage.response(self.str_cont3)
        self.window.close()
        
    def helpWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Help.Ui_Window_help()
        self.ui.setupUi(self.window)
        self.window.show()
        self.str_cont1 = self.ui.label_Help_Heading.text()
        self.str_cont2 = self.ui.label_Help_Content.text()
        self.window.show()
        manage.response("")
        manage.response(self.str_cont1)
        manage.response("")
        manage.response(self.str_cont2)
        self.window.close()
    
    
    def setupUi(self, MainWindow_voice):
        MainWindow_voice.setObjectName("MainWindow_voice")
        MainWindow_voice.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow_voice.resize(580, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow_voice.sizePolicy().hasHeightForWidth())
        MainWindow_voice.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        MainWindow_voice.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow_voice.setWindowIcon(icon)
        MainWindow_voice.setToolTipDuration(1)
        MainWindow_voice.setStyleSheet("background-color: rgb(223, 223, 223);")
        MainWindow_voice.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        MainWindow_voice.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow_voice)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setToolTipDuration(1)
        self.label_2.setText("")
        # self.label_2.setPixmap(QtGui.QPixmap(":/newPrefix/listening.gif"))
        self.movie = QMovie(":/newPrefix/listening.gif")
        self.label_2.setMovie(self.movie)
        self.startAnimation()
        self.label_2.setScaledContents(True)
        self.label_2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        MainWindow_voice.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow_voice)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 580, 21))
        self.menubar.setObjectName("menubar")
        self.menuVoice_Only = QtWidgets.QMenu(self.menubar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuVoice_Only.sizePolicy().hasHeightForWidth())
        self.menuVoice_Only.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menuVoice_Only.setFont(font)
        self.menuVoice_Only.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.menuVoice_Only.setTabletTracking(True)
        self.menuVoice_Only.setFocusPolicy(QtCore.Qt.TabFocus)
        self.menuVoice_Only.setToolTipDuration(1)
        self.menuVoice_Only.setAutoFillBackground(False)
        self.menuVoice_Only.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.menuVoice_Only.setTearOffEnabled(True)
        self.menuVoice_Only.setToolTipsVisible(True)
        self.menuVoice_Only.setObjectName("menuVoice_Only")
        self.menu_About = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menu_About.setFont(font)
        self.menu_About.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.menu_About.setToolTipDuration(1)
        self.menu_About.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.menu_About.setObjectName("menu_About")
        self.menu_Help_2 = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menu_Help_2.setFont(font)
        self.menu_Help_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.menu_Help_2.setToolTipDuration(1)
        self.menu_Help_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.menu_Help_2.setObjectName("menu_Help_2")
        MainWindow_voice.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_voice)
        self.statusbar.setObjectName("statusbar")
        MainWindow_voice.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow_voice)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.toolBar.setFont(font)
        self.toolBar.setToolTipDuration(-1)
        self.toolBar.setObjectName("toolBar")
        MainWindow_voice.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menubar.addAction(self.menuVoice_Only.menuAction())
        self.menubar.addAction(self.menu_Help_2.menuAction())
        self.menubar.addAction(self.menu_About.menuAction())
        
        
        self.menuVoice_Only.addAction(self.menuVoice_Only.menuAction())
        self.menuVoice_Only.hovered.connect(self.mainWindow)
        self.menu_About.addAction(self.menu_About.menuAction())
        self.menu_About.hovered.connect(self.aboutWindow)
        self.menu_Help_2.addAction(self.menu_Help_2.menuAction())
        self.menu_Help_2.hovered.connect(self.helpWindow)


        self.retranslateUi(MainWindow_voice)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_voice)

    def retranslateUi(self, MainWindow_voice):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_voice.setWindowTitle(_translate("MainWindow_voice", "AOS 1.0 - Main"))
        MainWindow_voice.setToolTip(_translate("MainWindow_voice", "Main Window"))
        self.menuVoice_Only.setToolTip(_translate("MainWindow_voice", "Voice Only Command"))
        self.menuVoice_Only.setTitle(_translate("MainWindow_voice", "Main"))
        self.menu_About.setToolTip(_translate("MainWindow_voice", "About"))
        self.menu_About.setTitle(_translate("MainWindow_voice", "About"))
        self.menu_Help_2.setToolTip(_translate("MainWindow_voice", "Help"))
        self.menu_Help_2.setStatusTip(_translate("MainWindow_voice", "Help"))
        self.menu_Help_2.setTitle(_translate("MainWindow_voice", "Help"))
        self.toolBar.setWindowTitle(_translate("MainWindow_voice", "toolBar"))
        
        
    def startAnimation(self):
        self.movie.start()
        
import image_assets


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow_voice = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_voice()
    ui.setupUi(MainWindow_voice)
    MainWindow_voice.show()
    sys.exit(app.exec_())
